version: "3.8"
services:
  server:
    image: xchange/server:1.0
    build:
      context: .
      dockerfile: services/server/Dockerfile
    depends_on:
      - mongo
    volumes:
      - type: bind
        source: .
        target: /usr/src/xchange
    ports:
      - "8200:8200"
    links:
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: spinelsun
      MONGO_INITDB_ROOT_PASSWORD: shelasa
    ports: 
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: spinelsun
      ME_CONFIG_MONGODB_ADMINPASSWORD: shelasa